areas/urls.py
from django.urls import path,re_path
from areas import views


urlpatterns = [
    re_path(r'^areas/$', views.AreasView.as_view(), name='areas'),
]

carts/urls.py
from carts import views
from django.urls import path,re_path

urlpatterns = [
    re_path(r'^carts/$', views.CartsView.as_view()),
]

meiduo/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admins/', include(('admins.urls','admins'), namespace='admins')),
    path('', include(('users.urls','users'), namespace='user')),
    path('', include(('contents.urls','contents'),namespace='content')),
    path('', include(('verifications.urls','verifications'),namespace='verification')),
    path('', include(('oauth.urls','oauth'),namespace='oauth')),
    path('', include(('areas.urls','areas'),namespace='areas')),
    path('', include(('goods.urls','goods'),namespace='goods')),
    re_path(r'^search/', include('haystack.urls')),
    path('', include(('carts.urls','carts'),namespace='carts')),
    path('', include(('orders.urls','carts'),namespace='orders')),
    path('', include(('payment.urls', 'payment'), namespace='payment')),
]

users/urls.py
from users import views
from django.urls import path,re_path

app_name = 'user'

urlpatterns = [
    path(r'register/', views.RegisterView.as_view()),
    re_path(r'^usernames/(?P<username>[a-zA-Z0-9_-]{5,20})/count/$', views.UsernameCountView.as_view()),
    re_path(r'^mobiles/(?P<mobile>1[0-9]\d{9})/count/$', views.MobileCountView.as_view()),
    re_path(r'^login/', views.LoginView.as_view(),name='login'),
    re_path(r'^logout/', views.LogoutView.as_view(),name='logout'),
    re_path(r'^info/', views.UserinfoView.as_view(), name='info'),
    re_path(r'^cart/', views.UserCartView.as_view(), name='cart'),
    re_path(r'^order/', views.UserOrderView.as_view(), name='order'),

    re_path(r'^change/', views.ChangePasswordView.as_view(), name='change_password'),

    re_path(r'^emails/', views.EmailView.as_view(), name='email'),
    re_path(r'^verification/$', views.VerifyEmailView.as_view(), name='verify_email'),
    re_path(r'^address/$', views.AddressView.as_view(), name='address'),
    re_path(r'^address/(?P<address_id>\d+)/$', views.UpdateDestroyAddressView.as_view(), name='address_update'),
    re_path(r'^address/default/(?P<address_id>\d+)/$', views.DefaultAddressView.as_view(), name='address_default'),
    re_path(r'^address/title/(?P<address_id>\d+)/$', views.UpdateTitleAddressView.as_view(), name='address_title'),
    re_path(r'^addresses/create/$', views.AddressCreateView.as_view(), name='address_create'),

    re_path(r'^browse_histories/$', views.UserBrowseHistory.as_view(), name='history'),
]

admins/views/user.py
from rest_framework.views import APIView
from django.views import View
from django.shortcuts import render,redirect
from rest_framework.permissions import IsAdminUser
from datetime import date
from users.models import Users
from orders.models import OrderInfo
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from datetime import timedelta
from goods.models import GoodsVisitCount,GoodsCategory
from django.core.paginator import Paginator,EmptyPage
from django.http import HttpResponseNotFound,HttpResponseForbidden,HttpResponse,JsonResponse
import re
from django.db import DatabaseError
import json

class UsersView(View):
    # 权限认证
    permission_classes = [IsAdminUser]
    # 渲染器指定
    renderer_classes = [JSONRenderer]

    def get(self,request,keyword,page_num):
        # print(keyword)
        user_list = []
        # 当不存在查询参数时，即返回所有用户信息
        if not keyword:
            users = Users.objects.filter(is_staff=False)
        else:
            users = Users.objects.filter(username__icontains=keyword, is_staff=False)
            if not users.exists():
                return render(request, 'user_admins.html', {'users': user_list})

        # for user in users:
        #     dic={
        #         "id": user.id,
        #         "name": user.username,
        #         "mobile": user.mobile if user.mobile else " ",
        #         "email": user.email if user.email else " "
        #     }
        #     user_list.append(dic)
        #
        # return render(request, 'user_admins.html', {'users': user_list})

        paginator= Paginator(users,2)
        total_page = paginator.num_pages

        #获取当前页的数据和总页数
        # page_dict={}
        # for i in range(total_page):
        try:
            page_users=paginator.page(page_num)
        except EmptyPage:
            return HttpResponseNotFound('当前页面不存在')

        user_list=[]
        for user in page_users:
            dic={
                    "id": user.id,
                    "name": user.username,
                    "mobile": user.mobile if user.mobile else " ",
                    "email": user.email if user.email else " "
                }
            user_list.append(dic)

            # page_dict[str(i)]=user_list

        context = {
            'page_users': user_list,
            'total_page': total_page,
            'page_num': page_num,
        }

        return render(request,'user_admins.html',context=context)

class UserAddView(View):
    # 权限认证
    permission_classes = [IsAdminUser]
    # 渲染器指定
    renderer_classes = [JSONRenderer]
    def post(self,request):

        data = json.loads(request.body)
        username = data.get('userr')
        password = data.get('password')
        email = data.get('email')
        mobile = data.get('mobile')

        # print(username)
        # print(password)
        # print(mobile)
        # print(email)


        ##校验参数,前后端逻辑相同
        ##判断参数是否齐全；all(【列表】)方法 ,判断数值是否为空，有一个为空，则返回false
        if not all([username, password]):
            return HttpResponseForbidden('缺少必填项')

        # 用户名是否为5-20个字符；
        if not re.match(r'^[a-zA-Z0-9_-]{5,20}$', username):
            return HttpResponseForbidden('请输入5-20个字符的用户名')

        # 密码是否为8-20个字符；
        if not re.match(r'^[0-9a-zA-Z]{8,20}$', password):
            return HttpResponseForbidden('请输入8-20个字符的密码')

        # 手机号码是否合法；
        if not re.match(r'^1\d{10}$', mobile):
            return HttpResponseForbidden('请输入正确的手机号码')

        #电子邮箱是否合法；
        if not re.match(r'^\w+@\w+\.\w+$', email):
            return HttpResponseForbidden('email格式不正确')

        #用户名和手机号不能重复
        if not Users.objects.filter(username=username) and not Users.objects.filter(mobile=mobile):
            try:  # 返回一个对象
                user = Users.objects.create_user(username=username, password=password, mobile=mobile,email=email)
                return JsonResponse({'code': 'ok','register_error':f'添加ID{user.id} 用户 成功'})

            except DatabaseError:
                return JsonResponse({'code': 'fail','register_error': '添加用户失败'})
        else:
            return JsonResponse({'code': 'fail', 'register_error': '用户名或手机号已存在'})

carts/views.py
import base64
import pickle
from itertools import chain
from django.shortcuts import render
from django.views import View
import json
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from goods import models
from django_redis import get_redis_connection
from goods.models import SKU


class CartsView(View):
    # 添加购物车，登录时存储到redis数据库，未登录时存储到cookie
    def post(self, request):
        # 接收参数,sku_id,count,selected
        json_dict = json.loads(request.body.decode())
        sku_id = json_dict.get('sku_id')
        count = json_dict.get('count')
        selected = json_dict.get('selected', True)

        # 校验
        if not all([sku_id, count]):
            return HttpResponseForbidden('缺少必传参数')

        try:
            models.SKU.objects.get(id=sku_id)
        except models.SKU.DoesNotExist:
            return HttpResponseForbidden('sku_id不存在')

        try:
            count = int(count)
            if count > 5 or count < 0:
                return HttpResponseForbidden('count值异常')
        except Exception as e:
            return HttpResponseForbidden('count错误')

        if selected:
            if not isinstance(selected, bool):  # 校验是否为布尔值
                return HttpResponseForbidden('selected 异常')
        # 判断用户是否登录
        user = request.user
        # 已登录，redis
        if user.is_authenticated:
            redis_conn = get_redis_connection('carts')
            # 增量计算
            redis_conn.hincrby(f'carts_{user.id}', sku_id, count)
            # 添加被选择的
            if selected:
                redis_conn.sadd(f'selected_{user.id}', sku_id)
            return JsonResponse({'code': '0', 'errmsg': '已保存到购物车'})
        # 未登录，cookie
        else:
            # 获取购物车的数据,或者创建新的cookie

            if request.COOKIES.get('carts'):  # 存在cookie时，解码内容
                cart_str = request.COOKIES.get('carts')
                b = cart_str.encode()
                s = base64.b64decode(b)
                cart_dict = pickle.loads(s)
            else:
                cart_dict = {}
            # 判断要添加的商品在cookie中是否存在
            if sku_id not in cart_dict.keys():  # 不存在时，新建
                cart_dict[sku_id] = {
                    'count': count,
                    'selected': selected
                }
            else:  # 存在时，进行同类增量计算
                o_count = cart_dict[sku_id]['count']
                cart_dict[sku_id] = {
                    'count': o_count + count,
                    'selected': selected
                }

            # 将cart_dict写入cookies
            cart_s = pickle.dumps(cart_dict)
            cart_b = base64.b64encode(cart_s)
            cart_st = cart_b.decode()

            response = JsonResponse({'code': '0', 'errmsg': '已添加到购物车'})
            response.set_cookie('carts', cart_st)

            return response

    # 查询购物车
    def get(self, request):
        user = request.user
        cart_dict_redis = {}
        cart_dict_cookies = {}

        if user.is_authenticated:  # 登录用户查询redis
            redis_conn = get_redis_connection('carts')

            # 查询hash列表数据（user_id，sku_id）和set数据（user_id,selected_sku_id）
            redis_sku_id = redis_conn.hgetall(f'carts_{user.id}')
            redis_selected = redis_conn.smembers(f'selected_{user.id}')

            # 重新构建一个字典,与cookie格式相同
            for sku_id, count in redis_sku_id.items():
                cart_dict_redis[int(sku_id)] = {
                    'count': int(count),
                    'selected': sku_id in redis_selected
                }

        # 查询未登录时的cookies数据
        if request.COOKIES.get('carts'):  # 存在cookie时，解码内容
            cart_str = request.COOKIES.get('carts')
            b = cart_str.encode()
            s = base64.b64decode(b)
            cart_dict_cookies = pickle.loads(s)

        # print("cart_dict_cookies:", cart_dict_cookies)

        # 合并登录数据和未登录数据,并构建出

        keys_redis = cart_dict_redis.keys()
        keys_cookies = cart_dict_cookies.keys()

        # 读取redis里的数据 和cookie里的数据
        skus_redis = SKU.objects.filter(id__in=keys_redis)
        skus_cookies = SKU.objects.filter(id__in=keys_cookies)

        # Check if either queryset is None before merging
        if skus_redis is not None and skus_cookies is not None:
            merged_skus = list(chain(skus_redis, skus_cookies))
        else:
            # Handle the case where either skus_redis or skus_cookies is None
            merged_skus = skus_redis if skus_cookies is None else skus_cookies


        sku_dict = []
        sku_repeat=[]
        for skuu in merged_skus:
            if skuu.id not in sku_repeat:
                sku_repeat.append(skuu.id)

                try:
                    count_redis = cart_dict_redis.get(skuu.id,{}).get('count', 0)
                    selected_redis = cart_dict_redis.get(skuu.id,{}).get('selected', False)
                    count_cookies = cart_dict_cookies.get(skuu.id,{}).get('count', 0)
                    selected_cookies = cart_dict_cookies.get(skuu.id,{}).get('selected', False)

                except Exception as e:
                    count_redis = 0
                    selected_redis = False

                    count_cookies = 0
                    selected_cookies = False

                total_count = count_redis + count_cookies
                t_selected = selected_redis or selected_cookies

                sku_dict.append(
                    {
                        'id': skuu.id,
                        'count': total_count,
                        'selected': str(t_selected),
                        'name': skuu.name,
                        # 'default_image_url': sku.default_image_url,
                        'price': str(skuu.price),
                        'amount': str(skuu.price * total_count)
                })

        context={
            'cart_skus': sku_dict
        }

        response = render(request, 'cart.html', context)

        #将cookies里的数据，同步到redis里，并且同时删除cookie里的数据（因为有可能随时登录）
        if user.is_authenticated and request.COOKIES.get('carts'):
            redis_conn = get_redis_connection('carts')

            for keys, values in cart_dict_cookies.items():
                count = values.get('count',0)
                selected = values.get('selected',False)

                if not redis_conn.hexists(f'carts_{user.id}',keys):  # redis不已存在时，新建
                    redis_conn.hset(f'carts_{user.id}', keys, count)
                    if selected:
                        redis_conn.sadd(f'selected_{user.id}', keys)
                else:  # 存在时，进行同类增量计算
                    o_c=int(redis_conn.hget(f'carts_{user.id}', keys) or 0)
                    n_c=o_c+count
                    redis_conn.hset(f'carts_{user.id}', keys, n_c)
                    if selected:
                        redis_conn.sadd(f'selected_{user.id}', keys)

            # 删除名为 'carts' 的 cookie
            response.delete_cookie('carts')

        return response

    #修改购物车
    def put(self,request):
        #接收和校验参数
        json_dict = json.loads(request.body.decode())
        sku_id = json_dict.get('sku_id')
        count = json_dict.get('count')
        selected = json_dict.get('selected', True)

        # 校验参数
        if not all([sku_id, count]):
            return HttpResponseForbidden('缺少参数')

        try:
            models.SKU.objects.get(id=sku_id)
        except models.SKU.DoesNotExist:
            return HttpResponseForbidden('商品sku_id不存在')

        try:
            count = int(count)
            if count < 0:
                return HttpResponseForbidden('商品count值异常')
        except Exception as e:
            return HttpResponseForbidden('商品count错误')

        if selected:
            if not isinstance(selected, bool):  # 校验是否为布尔值
                return HttpResponseForbidden('商品selected 异常')

        # 判断用户是否登录，登录用户覆盖写入sku_id,count,selected
        # 未登录用户，只能修改cookies里的内容
        cart_dict = {}
        if request.COOKIES.get('carts'):  # 存在cookie时，解码内容
            cart_str = request.COOKIES.get('carts')
            b = cart_str.encode()
            s = base64.b64decode(b)
            cart_dict = pickle.loads(s)

        user = request.user
        if user.is_authenticated:
            redis_conn=get_redis_connection('carts')
            redis_conn.hset(f'carts_{user.id}',sku_id,count)
            if selected:
                redis_conn.sadd(f'selected_{user.id}',sku_id)
            else: #去掉勾选
                redis_conn.srem(f'selected_{user.id}',sku_id)

            #将修改后的数据重新传
            cart_sku={
                'id': sku_id,
                'count': count,
                'selected': selected,
                'name': SKU.objects.get(id=sku_id).name,
                # 'default_image_url': sku.default_image_url,
                'price': SKU.objects.get(id=sku_id).price,
                'amount': SKU.objects.get(id=sku_id).price * count
            }

            response = JsonResponse({'code': '0', 'errmsg': '已修改购物车','cart_sku': cart_sku})

        else:
            cart_dict[sku_id] = {
                'count': count,
                'selected': selected
            }

            # 将cart_dict写入cookies
            cart_s = pickle.dumps(cart_dict)
            cart_b = base64.b64encode(cart_s)
            cart_str = cart_b.decode()

            #将修改后的数据重新传
            cart_sku = {
                'id': sku_id,
                'count': count,
                'selected': selected,
                'name': SKU.objects.get(id=sku_id).name,
                # 'default_image_url': sku.default_image_url,
                'price': SKU.objects.get(id=sku_id).price,
                'amount': SKU.objects.get(id=sku_id).price * count
            }

            response = JsonResponse({'code': '0', 'errmsg': '已修改购物车','cart_sku': cart_sku})
            response.set_cookie('carts', cart_str)

        return response

    #删除购物车
    def delete(self,request):
        # 获取参数
        json_dict = json.loads(request.body.decode())
        sku_id = json_dict.get('sku_id')

        # 判断sku_id是否存在

users/templates/login.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script> <!--导入vue-->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>  <!--导入ajax，进行异步请求，局部刷新数据-->
    <!--    <script href="../meiduo/users/templates/axios.min.js"></script>-->

    <title>美多商城-登录</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 80vh;
            margin: 0;
        }

        .register_con {
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: left; /* Center-align the text */
        }

        .l_con {
            text-align: left; /* Left-align the text within the .l_con div */
        }

        .l_con img {
            max-width: 20%;
        }


    </style>

</head>
<body>
<div class="login_top clearfix">
    <a href="index.html" class="login_logo"><img src=" "></a>
</div>
<div class="login_form_bg" id="app">
    <div class="login_form_wrap clearfix" v-cloak>
        <div class="login_banner fl"></div>
        <div class="slogan fl">商品美·种类多·欢迎光临</div>
        <div class="login form fr">
            <div class="login_title clearfix">
                <a class="cur">账户登录</a>
            </div>
            <div class="form_con">
                <div class="form_input cur">
                    <form method="post" class="login-form" @submit="on_submit" v-cloak>
                        {{ csrf_input }}
                        <label for="user_name">用户名：</label>
                        <input type="text" v-model="username" @blur="check_username" name="username" class="user_name">
                        <div v-show="error_username" class="user_error">请输入正确的用户名</div>
                        <div></div>


                        <label for="password">密码：</label>
                        <input type="password" v-model="password" @blur="check_password" name="password" class="pwd">
                        <div v-show="error_password" class="pwd_error">密码最少为8位，最长为20位</div>


                        <div> {{ password_errmsg }}</div>


                        <div class="more_input clearfix">
                            <input type="checkbox" v-model="remembered" name="remembered">
                            <label>记住登录</label>
                        </div>
                        <input type="submit" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
            <div class="third_party">
                <a @click="qq_login" class="qq_login">QQ</a>
                <a href="#" class="weixin_login">微信</a>
                <a href="register.html" class="register_btn">立即注册</a>
            </div>
        </div>
    </div>
    <div class="footer no-mp">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight@2016 北京美多商业股份有限公司Al1 Rights Reserved</p>
        <p>电话：010-****888
            京ICP备＊＊＊＊＊＊＊8号</p>
    </div>

    <script>
        function get_query_string(parameter_name) {
            // 获取当前页面的URL
            var url = window.location.href;

            // 使用正则表达式匹配URL中的查询参数部分
            var parameter_regex = new RegExp('[?&]' + parameter_name + '=([^&#]*)');

            // 使用exec方法从URL中提取参数值
            var match = parameter_regex.exec(url);

            // 如果找到匹配的参数，返回参数值，否则返回null
            if (match !== null) {
                return decodeURIComponent(match[1]);
            } else {
                return null;
            }
        }

    </script>

    <!--引入vue代码-->
    <script>
        const { createApp, ref } = Vue;

        const app = createApp({
            delimiters:['[[',']]'],
            data() {
                return {
                    username: "",
                    password: "",

                    error_username: false,
                    error_password: false,
                    remembered: false ,
                };
            },

            methods: {
                //检查账号
                check_username() {
                    // 用户名是5-20个字符，[a-zA-Z0-9_-]
                    // 定义正则
                    let regex0 = /[a-zA-Z0-9_-]{5,20}$/;
                    // 使用正则匹配用户名数据
                    if (regex0.test(this.username)) {
                        // 匹配成功，不展示错误提示信息
                        this.error_username = false;
                    } else {
                        // 匹配失败，展示错误提示信息
                        this.error_username = true;
                    }
                },


                // 校验密码
                check_password(){
                    let regex = /[0-9a-zA-Z]{8,20}$/;
                    if (regex.test(this.password)) {
                        this.error_password = false;
                    } else {
                        this.error_password = true;
                    }
                },


                // 监听表单提交事件
                on_submit() {
                    // Run validation checks
                    this.check_username();
                    this.check_password();


                    if (error_username.value == false && error_password.value==false ){
                        window.event.returnValue = true ;
                    }
                },
                //qq登录
                qq_login() {
                    let next = get_query_string('next') || '/';
                    let url = '/qq/login/?next=' + next;
                    axios.get(url, { responseType: 'json' })
                        .then(response => {
                        location.href = response.data.login_url;
                    })
                        .catch(error => {
                        console.log(error.response);
                    })
                }


            }
        });

        app.mount("#app");
    </script>
</body>
</html>

users/templates/place_order.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script> <!--导入vue-->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>  <!--导入ajax，进行异步请求，局部刷新数据-->
    <title>美多商城-订单确认</title>
    <style></style>
</head>
<body>
<div id="app">
    <div class="header_con">
        <div class="header" v-cloak>
            <div class="welcome fL">欢迎来到美多商城！</div>
            <div class="fr">
                <div v-if="username" class="login_btn fl">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="/logout">退出</a>
                </div>
                <div v-else class="login_btn fl">
                    <a href="/login">登录</a>
                    <span>|</span>
                    <a href="/register">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="/info">用户中心</a>
                    <span>|</span>
                    <a href="/carts">我的购物车</a>
                    <span>|</span>
                    <a href="/orders">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    <div>
        <h3>确认收货地址</h3>
    </div>
    <div>
        <dl>
        {% if addresses %}
            {% load my_filters %}
        <dt>寄送到：</dt>
        {% for address in addresses %}
            <dd @click=" nowsite = {{address.id}} "><input type="radio" v-model="nowsite" :value="{{address.id}}">
            {{address.province}}&nbsp;&nbsp;{{address.city}}&nbsp;&nbsp;{{address.district}}&nbsp;&nbsp;
                ({{address.receiver | hide_middle_name}} 收)&nbsp;&nbsp;{{address.mobile | hide_middle}}</dd>
        {% endfor %}
        {% endif %}
        </dl>
        <a href="{% url 'user:address' %}">编辑收货地址</a>
    </div>
    <h3>支付方式</h3>
    <div>
        <input type="radio" name="pay_method" value="1" v-model="pay_method">
        <label>货到付款</label>
        <input type="radio" name="pay_method" value="2" v-model="pay_method">
        <label>支付宝</label>
    </div>
    <h3>商品列表</h3>
    <table>
  <thead>
    <tr>
        <th>商品名称</th>
        <th>商品价格</th>
        <th>商品数量</th>
        <th>小计</th>
    </tr>
  </thead>
    <tbody>
    {% for sku in skus %}
    <tr>
        <td>{{sku.name}}</td>
        <td>{{sku.price}}元</td>
        <td>{{sku.count}}</td>
        <td>{{sku.amount}}元</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    <h3>总金额结算</h3>
    <div>
        <div>共<em>{{total_count}}</em>件商品，总金额{{total_amount}}</div>
        <div>运费：<b>{{freight}}元</b></div>
        <div>实付款：<b>{{total_payment}}元</b></div>
    </div>
    <div>
        <button @click="on_order_submit" id="order_btn">提交订单</button>
    </div>
    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****88R 京ICP奋*＊＊＊＊＊＊8号</P>
    </div>
</div>
</body>
<script>
    let default_address_id = (typeof {{ user.default_address_id }} !== 'undefined') ? {{ user.default_address_id }} : null;
    let payment_amount = (typeof {{ total_amount }} !== 'undefined') ? {{ total_amount }} : 0;
</script>

<script>
    const { createApp, ref } = Vue;

    const app = createApp ({
    delimiters: ['[[', ']]'],
    data() {
        this.username=this.getCookie('username');
        this.default_address_id=default_address_id;
        this.payment_amount= payment_amount;

        return {
            order_submitting:false,
            pay_method:2,
            nowsite:'',
        };
    },
    created() {
    // 在组件创建时，将默认地址ID设置为nowsite的值
    this.nowsite = this.default_address_id;
  },
    methods: {
    getCookie(name) {
        const cookies = document.cookie.split('; ');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].split('=');
            if (cookie[0] === name) {
            return cookie[1];
            }
        }
            return null;
    },

    // 提交订单
    on_order_submit(){
        if(!this.nowsite){
         alert('请选择收货地址');
         return;
         }
        if (!this.pay_method){
         alert('请选择支付方式');
         return;
         }
        if (this.order_submitting==false){
         this.order_submitting=true;
         let url='/orders/commit/';
            axios.post(url,
                {
                address_id:this.nowsite,
                pay_method:parseInt(this.pay_method)
                },{
                headers:{
                    'X-CSRFToken':this.getCookie('csrftoken')
                },
                responseType:'json'
                })
            .then(response => {
                this.order_submitting=false;
                if(response.data.code=='0'){
                    location.href='/orders/success/?order_id='+response.data.order_id+
                                    '&payment_amount='+this.payment_amount+'&pay_method='+this.pay_method;
                    console.log(response.data.order_id)
                }else if(response.data.code=='406'){
                    location.href='/login/?next=/orders/settlement';
                }else{
                    alert(response.data.errmsg);
                    }
                })
                .catch(error=>{
                 this.order_submitting=false;
                 console.log(error.response);
                })
            }},
        },
    });
    app.mount("#app");
</script>
</html>