areas/urls.py
from django.urls import path,re_path
from areas import views


urlpatterns = [
    re_path(r'^areas/$', views.AreasView.as_view(), name='areas'),
]

goods/urls.py
from django.urls import path,re_path
from goods import views

app_name = 'goods'
urlpatterns = [
    re_path(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)/(?P<sort>.*)$', views.GoodsListView.as_view(), name='goodslist'),
    re_path(r'^detail/(?P<sku_id>\d+)/$', views.DetailView.as_view(),name='detail'),
    re_path(r'^hot/(?P<category_id>\d+)/$',views.HotView.as_view(),name='hot'),
    re_path(r'^detail/visit/(?P<category_id>\d+)/$',views.DetailVisitView.as_view(),name='visit_count'),
]

meiduo/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admins/', include(('admins.urls','admins'), namespace='admins')),
    path('', include(('users.urls','users'), namespace='user')),
    path('', include(('contents.urls','contents'),namespace='content')),
    path('', include(('verifications.urls','verifications'),namespace='verification')),
    path('', include(('oauth.urls','oauth'),namespace='oauth')),
    path('', include(('areas.urls','areas'),namespace='areas')),
    path('', include(('goods.urls','goods'),namespace='goods')),
    re_path(r'^search/', include('haystack.urls')),
    path('', include(('carts.urls','carts'),namespace='carts')),
    path('', include(('orders.urls','carts'),namespace='orders')),
    path('', include(('payment.urls', 'payment'), namespace='payment')),
]

goods/models.py
from django.db import models
from users.utils import BaseModel



#将mysql中的已存在的表格引入到django模型中
class ImageStorage(BaseModel):
    title=models.CharField(max_length=20,verbose_name='图片名称')
    image_data=models.BinaryField(max_length=256,verbose_name='二进制图片',null=True)

    class Meta:
        db_table = 'tb_image_data'
        verbose_name = '二进制图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class GoodsCategory(BaseModel):
    """商品类别,自关联，类似于省市级的表"""
    name = models.CharField(max_length=20, verbose_name='商品类别名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE, verbose_name='商品父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    group = models.ForeignKey(GoodsChannelGroup,on_delete=models.CASCADE, verbose_name='频道组名')
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='一级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='品牌名称')
    logo = models.ImageField(verbose_name='品牌图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='spu名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌名称')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别名称')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别名称')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别名称')
    sales = models.IntegerField(default=0, verbose_name='spu销量')
    comments = models.IntegerField(default=0, verbose_name='spu评价数')
    desc_detail = models.TextField(default='', verbose_name='spu详细介绍')
    desc_pack = models.TextField(default='', verbose_name='spu包装信息')
    desc_service = models.TextField(default='', verbose_name='spu售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='sku名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='spu名称')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='商品类别名称')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品市场价')
    stock = models.IntegerField(default=0, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    comments = models.IntegerField(default=0, verbose_name='商品评价数')
    is_launched = models.BooleanField(default=True, verbose_name='商品是否上架销售')
    default_image_url = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='商品默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku名称')
    image = models.ImageField(verbose_name='商品图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='SPU名称')
    name = models.CharField(max_length=20, verbose_name='spu规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='spu规格名称')
    value = models.CharField(max_length=20, verbose_name='规格选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku名称')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='spu规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格选项')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)


class  GoodsVisitCount(BaseModel):
    category = models.ForeignKey(GoodsCategory,on_delete=models.CASCADE,verbose_name='商品分类')
    counts = models.IntegerField(verbose_name='访问量',default=0)
    date = models.DateField(auto_now_add=True,verbose_name='统计日期')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计商品访问量'
        verbose_name_plural = verbose_name

# docker run -d --name tracker -p 22122:22122 -e GROUP_NAME=group1 -v C:/Users/KDG/meiduo/var/fdfs/tracker:/var/fdfs delron/fastdfs tracker
# docker run -d --name storage -p 23000:23000 -e IP=localhost -e TRACKER_SERVER=192.168.0.4:22122 -v C:/Users/KDG/meiduo/var/fdfs/storage:/var/fdfs delron/fastdfs storage
#
# 与docker建立连接
# from fdfs_client.client import Fdfs_client
# import mutagen
# import requests
#
# client=Fdfs_client('C:/Users/KDG/meiduo/fastdfs/client.conf')
# ret = client.upload_by_filename('C:/Users/KDG/Desktop/cat.jpeg')
# print(ret)

goods/views.py
import json

from django.shortcuts import render
from django.views import View
from django.http import HttpResponse,HttpResponseForbidden,HttpResponseNotFound,JsonResponse
from contents.views import get_categories
from django.core.paginator import Paginator,EmptyPage
from goods.models import GoodsCategory,SKU,SKUSpecification,SPUSpecification,SpecificationOption,GoodsVisitCount
from django.utils import timezone
from datetime import datetime


#封装面包屑导航函数
def breadcrumb(category):
    # 面包屑导航 ,自行判断为几级标签
    breadcrumb = {
        'cat1': '',
        'cat2': '',
        'cat3': ''
    }

    if not category.parent: #没有父级时为一级标签
        breadcrumb['cat1'] = category

    elif category.subs.count()==0: #没有子级时为三级标签
        breadcrumb['cat1']= category.parent.parent
        breadcrumb['cat2'] = category.parent
        breadcrumb['cat3'] = category

    else: #为二级标签s
        breadcrumb['cat1'] = category.parent
        breadcrumb['cat2'] = category

    return breadcrumb

# 通过sku_id ，查询所有的规格类specs
# #再通过specs查询查询所有的规格选项options
# #构造数据结构，包括specs和options
# specs_dic={
#     spec1:[options],
#     spec2:[options]
# }
# #将数据传入前段，并渲染到网页上，再根据当前选择的sku_id将当前商品数据进行选定
# #还要实现交互效果，即改变option，局部刷新sku_id 以及商品图片和评价等


class DetailVisitView(View):
    #统计商品访问量
    def post(self,request,category_id):
        #传入参数和校验参数
        try:
            goods=GoodsCategory.objects.get(id=category_id)
        except GoodsCategory.DoesNotExist:
            return HttpResponseForbidden('category_id不存在')

        # # 统计访问量
        # t = timezone.localdate()
        # date_str = '%d-%02d-%02d' % (t.year, t.month, t.day)
        # date = datetime.strptime(date_str, '%Y-%m-%d')
        #
        # try:
        #     good_visit=goods.goodsvisitcount_set.get(date=date,category_id=category_id)
        #     good_visit.count=good_visit.count+1
        #     good_visit.save()
        # except GoodsVisitCount.DoesNotExist:
        #     GoodsVisitCount.objects.create(date=date, category_id=category_id, count=1)
        # return JsonResponse({'code':0,'errmsg':'已完成统计'})

        # 获取当天的日期
        t=timezone.localdate()
        # 分别读取出年月日
        date_str='%d-%02d-%02d' % (t.year,t.month,t.day)
        date=datetime.strptime(date_str,'%Y-%m-%d')
        try:
            goods_visit=GoodsVisitCount.objects.get(date=date,category=goods)
        except GoodsVisitCount.DoesNotExist:
            goods_visit=GoodsVisitCount() #实例化一个对象
        try:
            goods_visit.category=goods
            goods_visit.date=date
            goods_visit.counts=goods_visit.counts+1
            goods_visit.save()
        except Exception as e:
            return JsonResponse({'code': 420, 'errmsg': '统计搜索记录失败'})

        return JsonResponse({'code': 0, 'errmsg': '统计搜索记录成功'})

#有静态化页面之后，直接渲染html就行
# class DetailView(View):
#     def get(self,request,sku_id):
#         #接收参数
#         try:
#             sku=SKU.objects.get(id=sku_id)
#             return render(request, '{}.html'.format(sku_id))
#         except SKU.DoesNotExist:
#             return render(request,'404.html')

# 建立商品详情页面
class DetailView(View):
    def get(self,request,sku_id):
        #接收参数
        try:
            sku=SKU.objects.get(id=sku_id)
        except SKU.DoesNotExist:
            return render(request,'404.html')

        #插入商品分类导航
        category = get_categories()

        #插入面包屑导航栏
        breadc = breadcrumb(sku.category)


        # 要求所有规格必须填写
        # # 构建当前规格键
        # # 找到sku对应的SKUSpecification对象
        # sku_specs = sku.specs.order_by('spec_id')
        # sku_key=[]
        # # 循环读取所有规格的选项卡
        # for spec in sku_specs:
        #     sku_key.append(spec.option.id)
        # # 获取当前商品的所有SKU
        # skus = sku.spu.sku_set.all()
        # # 构建不同规格参数（选项）的sku字典
        # spec_sku_map = {}
        # for s in skus:
        #     # 获取sku的规格参数
        #     s_specs = s.specs.order_by('spec_id')
        #     # 用于形成规格参数-sku字典的键
        #     key = []
        #     for spec in s_specs:
        #         key.append(spec.option.id)
        #     # 向规格参数-sku字典添加记录
        #     spec_sku_map[tuple(key)] = s.id
        # # 获取当前商品的规格信息
        # goods_specs = sku.spu.specs.order_by('id')
        # # 若当前sku的规格信息不完整，则不再继续
        # if len(sku_key) < len(goods_specs):
        #     return
        # for index, spec in enumerate(goods_specs):
        #     # 复制当前sku的规格键
        #     key = sku_key[:]
        #     # 该规格的选项
        #     spec_options = spec.options.all()
        #     for option in spec_options:
        #         # 在规格参数sku字典中查找符合当前规格的sku
        #         key[index] = option.id
        #         option.sku_id = spec_sku_map.get(tuple(key))
        #     spec.spec_options = spec_options


        # 获取全部的options
        # 构建当前规格键
        # 找到sku对应的SKUSpecification对象下的所有规格信息
        # spu = sku.spu
        # sku_specs=spu.specs.all()
        #
        # goods_specs = {}
        # # 循环读取当前商品的所有规格信息
        # for sku_spec in sku_specs:
        #     value=[]
        #     # 循环遍历规格选项
        #     for option in sku_spec.options.all():
        #         value.append(option.value)
        #     goods_specs[sku_spec.name] = value

        # 获取当前options

        spu = sku.spu
        sku_specs=spu.specs.filter(spu=spu)

        goods_specs = {}
        for sku_spec in sku_specs:
            value=[]
            options=sku.specs.filter(spec=sku_spec)
            for option in options:
                value.append(option.option)
            goods_specs[sku_spec.name]=value

        #查询sku
        context={
            'category': category,
            'breadcrumb': breadc,
            'sku': sku,
            'specs': goods_specs,
        }
        #响应
        return render(request,'detail.html',context)



class HotView(View):
    #商品热销排行,取销量最高的前两个
    def get(self,request,category_id):
        skus =SKU.objects.filter(category_id=category_id,is_launched=True).order_by('-sales')[:2]

        #序列化器
        hot_skus=[]
        for sku in skus:
            hot_skus.append({
                'id': sku.id,
                # 'default_image_url': sku.default_image_url,
                'name': sku.name,
                'price': sku.price
            })
        return JsonResponse({'code': 0,'errmsg': 'ok','hot_skus': hot_skus})



class GoodsListView(View):

    def get(self,request,category_id,page_num,sort):
        try:
            category=GoodsCategory.objects.get(id=category_id)
        except GoodsCategory.DoesNotExist:
            return HttpResponseForbidden('无法查询category_id')

        categories = get_categories()

        #面包屑查询
        breadc = breadcrumb(category)

        #将前端传进来的sort字段，转换为数据库中的字段属性
        sort=request.GET.get('sort','default')
        if sort == 'price':
            sort_field='price'
        elif sort == 'hot':
            sort_field='-sales' #销量倒序排列，从高到低
        else:
            sort='defalut'
            sort_field='create_time'


        #分页和排序查询（sku信息）
        skus=category.sku_set.filter(is_launched=True).order_by(sort_field)
        #将所有产品进行分页
        paginator= Paginator(skus,5)
        #获取当前页的数据和总页数
        try:
            page_skus=paginator.page(page_num)
        except EmptyPage:
            return HttpResponseNotFound('当前页面不存在')
        total_page=paginator.num_pages



        context={
            'category_id': category_id,
            'categories': categories,
            'breadcrumb': breadc,
            'page_skus': page_skus,
            'total_page': total_page,
            'page_num': page_num,
            'sort': sort,
        }


        return render(request,'list.html',context=context)

goods/templates/list.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="../../../../static/simplePagination.css"></link>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script> <!--导入vue-->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>  <!--导入ajax，进行异步请求，局部刷新数据-->
    <!--    由于静态文件存储在static路由下，所以通过后退位置../-->
    <script src="../../../../static/jquery.min.js"></script>
    <script src="../../../../static/jquery.simplePagination.js"></script>

    <link rel="stylesheet" type="text/css" href="../../../static/simplePagination.css"></link>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script> <!--导入vue-->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>  <!--导入ajax，进行异步请求，局部刷新数据-->
    <!--    由于静态文件存储在static路由下，所以通过后退位置../-->
    <script src="../../../static/jquery.min.js"></script>
    <script src="../../../static/jquery.simplePagination.js"></script>

    <meta charset="UTF-8">
    <title>商品列表</title>

</head>

<body>

<div id="app">
    <div class="header_con">


        <div class="header" v-cloak>

            <div class="welcome fl">欢迎来到美多商城！</div>
            <div class="fr">
                <div v-if="username" class="login_btn fl">
                    欢迎您：<em>[[ username]]</em>
                    <span>|</span>
                    <a href="/logout">退出</a>
                </div>
                <div v-else class="login_btn fl">
                    <a href="/login">登录</a>
                    <span>|</span>
                    <a href="/register">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="/info">用户中心</a>
                    <span>|</span>
                    <a href="cart.html">我的购物车</a>
                    <span>|</span>
                    <a href="user_center_order.html">我的订单</a>
                </div>
            </div>
        </div>
    </div>
    <div class="search_bar clearfix">
        <a href="#" class="logo fl"><img src="#"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
        <div class="guest_cart fr">
            <a href="/carts" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">2</div>
            <ul class="cart_goods_show">
                <li>
                    <img src="#" alt="商品图片">
                    <h4>华为 HUAWEI P10 PLus 6GB+64GB 钻雕金 移动联通电信4G手机 双卡双待</h4>
                    <div>1</div>
                </li>
                <li>
                    <img src="#" alt="商品图片">
                    <h4>Apple iPhoneX 646B 深空灰色移动联通电信46手机</h4>
                    <div>1</div>
                </li>
            </ul>
        </div>
    </div>

    <div class="navbar_con">
        <div class="navbar">
            <div class="sub_menu_con fl">
                <div><h3>商品信息</h3>
                    <ul class="sub_menu">
                        {% for group in categories %}
                        <li>
                            <div class="level1">
                                {% for channel in group.channels %}
                                <a href="{{ channel.url }}" @mouseover="toggleShow1(true)"
                                   @mouseout="toggleShow1(false)">{{ channel.name }}</a>
                                {% endfor %}
                            </div>

                            <div class="level2" v-show="show1">
                                {% for cat2 in group.sub_cats %}
                                <div class="list_group">
                                    <div class="group_name fl" @mouseover="toggleShow2(true)"
                                         @mouseout="toggleShow2(false)">{{ cat2.name }} &gt;
                                    </div>

                                    <div class="group_detail fl" v-show="show2">
                                        {% for cat3 in cat2.sub_cats %}
                                        <a href='#' @mouseover="toggleShow3(true)" @mouseout="toggleShow3(false)">
                                            {{cat3.name }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">真划算</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>

</div>

<div class="breadcrumb">
    <a href="#">{{breadcrumb.cat1.name}}</a>
    <span>|</span>
    <a href="#">{{breadcrumb.cat2.name}}</a>
    <span>|</span>
    <a href="#">{{breadcrumb.cat3.name}}</a>
</div>

<div class="r_wrap fr clearfix">
    <div class="sort_bar">
        <a href="{% url 'goods:goodslist' category_id=category_id page_num=1 sort=sort %}" {% if sort == "default" %}class="active"{% endif %}>默认</a>
        <a href="{% url 'goods:goodslist' category_id=category_id page_num=1 sort=sort %}" {% if sort == "price" %}class="active"{% endif %}>价格</a>
        <a href="{% url 'goods:goodslist' category_id=category_id page_num=1 sort=sort %}" {% if sort == "hot" %}class="active"{% endif %}>销量</a>
    </div>
</div>

<div>
<ul class="goods_type_list clearfix">
    {% for sku in page_skus %}
    <li>

<!--        <a href="detail.html"><img src="{{sku.default_image_url}}"></a>-->
        <a href="{%url 'goods:detail' sku.id %}"><img src="{{sku.default_image_url}}"></a>

        <h4><a href="{%url 'goods:detail' sku.id %}">{{sku.name}}</a> </h4>
        <div class="operate">
            <span class="price">{{sku.price}}</span>
            <span class="unit">台</span>
            <a href="#" class="add_goods" title="加入购物车"></a>
        </div>
    </li>
    {% endfor %}
</ul>
</div>

<!--设置分页-->
<div class="pagination" id="pageDIV">

</div>

</div>



<script type="text/javascript">
        $(function() {
        // 为具有指定选择器的元素设置分页
        $('#pageDIV').pagination({
            currentPage:{{page_num}},
            pages:{{total_page}},
            itemsOnPage:5,
            prevText:'上一页',
            nextText:'下一页',
            cssStyle: 'light-theme',
            onPageClick(getCurrentPage){
                location.href='/list/{{category_id}}/'+getCurrentPage+'/?sort={{sort}}'
        },
        })
    });

    //提取cookie
    function getCookie(name){
        let r= document.cookie.match('\\b'+name+'=([^;]*)\\b')
        return r ? r[1]:undefined;
    };

</script>
</body>





<script>

    const { createApp, ref } = Vue ;

    const app = createApp({
        delimiters:['[[',']]'],
        data() {
            return {
                show1:false,
                show2:false,

                username:getCookie('username'),

            };
        },

        methods: {
            //监听鼠标是否停留在当前类别位置
           toggleShow1(isVisible) {
                this.show1= isVisible;
            },

            toggleShow2(isVisible) {
                this.show1= isVisible;
                this.show2 = isVisible;
            },

              toggleShow3(isVisible) {
                this.show1 = isVisible;
                this.show2 = isVisible;
            }
        },

    });

    app.mount("#app");

</script>


</html>